=== MigleMic/University_Tasks/IT/BookstoreSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
targetNamespace="https://www.amazon.de" 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:mano="https://www.amazon.de">
    <xs:element name="Bookstore" type="mano:BookstoreType">
        <xs:key name="authorId">
            <xs:selector xpath="mano:authors/mano:author"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="ReferenceToAuthorId" refer="mano:authorId">
            <xs:selector xpath="mano:books/mano:book/mano:author"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name= "BookstoreType">
        <xs:sequence>
            <xs:element name="authors" type="mano:authorsType"/>
            <xs:element name="books" type="mano:booksType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="authorsType">
        <xs:sequence>
            <xs:element name="author" type="mano:authorType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>    
    </xs:complexType>

    <xs:complexType name="authorwithAttributeType">
        <xs:choice>
            <xs:sequence>
                <xs:element name="firstname" type="xs:string"/>
                <xs:element name="lastname" type="xs:string"/>  
            </xs:sequence>
            <xs:element name="pseudonym" type="xs:string"/>
        </xs:choice>    
        <xs:attribute name="id" type="mano:authorIdType"/>
    </xs:complexType>         

    <xs:complexType name="authorType">
        <xs:complexContent>
            <xs:extension base="mano:authorwithAttributeType">
                <xs:sequence>
                    <xs:element name="dead" type="xs:boolean" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="authorIdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="booksType">
        <xs:sequence>
            <xs:element name="book" type="mano:bookType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="comics" type="mano:comicsType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bookType" mixed="true">
        <xs:sequence>
            <xs:element name="isbn" type="mano:isbnAttributeType"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="author" type="mano:bookAuthorType"/>
            <xs:element name="cover" type="xs:string"/>
            <xs:element name="details" type="mano:bookDetailsType"/>
            <xs:element name="comments" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="comicsType">
        <xs:complexContent>
            <xs:restriction base="mano:bookType"> 
                <xs:sequence> 
                    <xs:element name="isbn" type="mano:isbnAttributeType"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="author" type="mano:bookAuthorType"/>
                    <xs:element name="cover" type="xs:string" fixed="Illustrated paperback"/>
                    <xs:element name="details" type="mano:bookDetailsType"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType> 

    <xs:simpleType name="isbnType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}[-][0-9]{10}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="isbnAttributeType">
        <xs:simpleContent>
            <xs:extension base="mano:isbnType"> 
                <xs:attribute name="identifier" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="bookAuthorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="ref" type="mano:authorIdType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="bookDetailsType"> 
         <xs:sequence>
            <xs:element name="genres" type="mano:genresType"/>
            <xs:element name="pages" type="xs:integer"/>
            <xs:element name="priceChange" type="mano:priceChangeList"/>
            <xs:element name="currency" type="mano:currencyType"/>
            <xs:element name="amount" type="xs:integer"/>
            <xs:element name="publicationdate" type="xs:date"/>
            <xs:element name="readingAge" type="mano:readingAgeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType> 

    <xs:complexType name="ageType"> 
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="limit" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="readingAgeType"> 
        <xs:simpleContent>
            <xs:restriction base="mano:ageType">
                <xs:minInclusive value="5"/>
                <xs:maxInclusive value="18"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="priceChangeList">
        <xs:list itemType="xs:decimal"/>
    </xs:simpleType>
    
    <xs:complexType name="genresType">
        <xs:sequence>
                <xs:element name="genre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
   </xs:complexType>

    <xs:complexType name="currencyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="mano:currencyEnum"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="currencyEnum">
        <xs:restriction base="xs:string">
                <xs:enumeration value="Dollars"/>
                <xs:enumeration value="Euros"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== MigleMic/University_Tasks/IT/IT_Bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bookstore xmlns="https://www.amazon.de"
xsi:schemaLocation="https://www.amazon.de BookstoreSchema.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <authors>
    <author id="a1">
        <firstname>William</firstname>
        <lastname>Shakespeare</lastname>
        <dead>true</dead>
    </author>
    <author id="a2">
        <firstname>Stephen</firstname>
        <lastname>King</lastname>
    </author>
    <author id="a3">
        <firstname>Neil</firstname>
        <lastname>Gaiman</lastname>
    </author>
    <author id="a4">
        <pseudonym>Mo Xiang Tong Xiu</pseudonym>
    </author>
    <author id="a5">
        <firstname>George R.R.</firstname>
        <lastname>Martin</lastname>
    </author>
 </authors>
 <books>
    <book>
        <isbn identifier="ISBN-13">979-8651027460</isbn>
        <name>Macbeth</name>
        <author ref="a1"/>
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Drama</genre>
                <genre>Historical Fiction</genre>
            </genres>
            <pages>108</pages>
            <priceChange>9.99 8.79</priceChange>
            <currency type="Euros"/>
            <amount>5</amount>
            <publicationdate>2020-06-14</publicationdate>
        </details>
        <comments>There is an audio book</comments>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-1774260395</isbn>
        <name>Hamlet</name>
        <author ref="a1"/>
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Drama</genre>
                <genre>Historical Fiction</genre>
            </genres>
            <pages>172</pages>
            <priceChange>8.55 9.99</priceChange>
            <currency type="Euros"/>
            <amount>15</amount>
            <publicationdate>2020-11-24</publicationdate>
        </details>    
    </book>
    <book>
        <isbn identifier="ISBN-13">979-8651027460</isbn>
        <name>A Midsummer Night's Dream</name>
        Fantasy drama about faes
        <author ref="a1"/>
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Drama</genre>
                <genre>Fiction</genre>
                <genre>Fantasy</genre>
            </genres>
            <pages>275</pages>
            <priceChange>7.21 6.99</priceChange>
            <currency type="Euros"/>
            <amount>20</amount>
            <publicationdate>2008-06-15</publicationdate>
        </details>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-1444708158</isbn>
        <name>The Dark Half</name>
        <author ref="a2"/>
        <cover>Hard cover</cover>
        <details>
            <genres> 
                <genre>Horror</genre>
                <genre>Fiction</genre>
                <genre>Thriller</genre>
            </genres>
            <pages>480</pages>
            <priceChange>9.79 15.85</priceChange>
            <currency type="Euros"/>
            <amount>6</amount>
            <publicationdate>2011-11-10</publicationdate>
        </details>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-1982103521</isbn>
        <name>The Mist</name>
        <author ref="a2"/>
        <cover>Hard cover</cover>
        <details>
            <genres> 
                <genre>Horror</genre>
                <genre>Thriller</genre>
                <genre>Fiction</genre>
            </genres>
            <pages>176</pages>
            <priceChange>12.00 15.99</priceChange>
            <currency type="Euros"/>
            <amount>50</amount>
            <publicationdate>2018-06-05</publicationdate>
        </details>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-1444720686</isbn>
        <name>Bag of Bones</name>
        <author ref="a2"/>
        <cover>Hard cover</cover>
        <details>
            <genres> 
                <genre>Horror</genre>
                <genre>Fiction</genre>
                <genre>Thriller</genre>
            </genres>
            <pages>672</pages>
            <priceChange>11.09 8.99 10.57</priceChange>
            <currency type="Euros"/>
            <amount>24</amount>
            <publicationdate>2011-08-04</publicationdate>
        </details>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-0393356182</isbn>
        <name>Norse Mythology</name>
        Collection of norse mythology and their gods.
        <author ref="a3"/>
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Fantasy</genre>
                <genre>Myth</genre>
            </genres>
            <pages>304</pages>
            <priceChange>10.19 8.79 15.55</priceChange>
            <currency type="Euros"/>
            <amount>4</amount>
            <publicationdate>2018-03-06</publicationdate>
        </details>
        <comments>There is an audio book</comments>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-1524796280</isbn>
        <name>Fire and Blood</name>
        <author ref="a5"/>
        <cover>Hard Cover</cover>
        <details>
            <genres> 
                <genre>Fantasy</genre>
                <genre>Fiction</genre>
            </genres>
            <pages>736</pages>
            <priceChange>27.99 30.99 36.58</priceChange>
            <currency type="Dollars"/>
            <amount>5</amount>
            <publicationdate>2018-11-20</publicationdate>
        </details>
    </book>    
    <book>
        <isbn identifier="ISBN-13">978-0553103540</isbn>
        <name>Game of Thrones</name>
        <author ref="a5"/>
        <cover>Hard Cover</cover>
        <details>
            <genres> 
                <genre>Fantasy</genre>
                <genre>Fiction</genre>
            </genres>
            <pages>694</pages>
            <priceChange>31.49 35.99 30.49</priceChange>
            <currency type="Dollars"/>
            <amount>41</amount>
            <publicationdate>1996-08-01</publicationdate>
        </details>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-1648279195</isbn>
        <name>Grandmaster of Demonic Cultivation</name>
        A demonic cultivator tries to solve a murder.
        <author ref="a4"/>
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Fantasy</genre>
                <genre>Action</genre>
            </genres>
            <pages>396</pages>
            <priceChange>14.99 18.99 16.99</priceChange>
            <currency type="Euros"/>
            <amount>4</amount>
            <publicationdate>2021-12-14</publicationdate>
        </details>
    </book>
    <book>
        <isbn identifier="ISBN-13">978-1648279171</isbn>
        <name>Heaven Official's Blessing</name>
        A love story between a God and a  Ghost King.
        <author ref="a4"/>
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Fantasy</genre>
                <genre>Drama</genre>
            </genres>
            <pages>432</pages>
            <priceChange>14.99 18.99 16.99</priceChange>
            <currency type="Euros"/>
            <amount>0</amount>
            <publicationdate>2021-12-14</publicationdate>
            <readingAge limit="Mature">16</readingAge>
        </details>
    </book>
    <book> 
        <isbn identifier="ISBN-13">978-1648279218</isbn>
        <name>The Scum Villain's Self-Saving System</name>
        A man transmigrated into old xianxia world
        <author ref="a4"/>
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Fantasy</genre>
                <genre>Comedy</genre>
            </genres>
            <pages>352</pages>
            <priceChange>14.99 18.99 16.99</priceChange>
            <currency type="Euros"/>
            <amount>2</amount>
            <publicationdate>2021-12-14</publicationdate>
            <readingAge limit="Mature">16</readingAge>
        </details>
    </book> 
    
   <!--
    <comics>
        <isbn identifier="ISBN-13">979-8651027425</isbn>
        <name>Macbeth</name>
        <author ref="a3"/>    
        <cover>Paperback</cover>
        <details>
            <genres> 
                <genre>Drama</genre>
                <genre>Historical Fiction</genre>
            </genres>
            <pages>108</pages>
            <priceChange>9.99 8.79</priceChange>
            <currency type="Euros"/>
            <amount>5</amount>
            <publicationdate>2020-06-14</publicationdate>
            <readingAge limit="Mature">15</readingAge> 
        </details>
    </comics>
    -->

    <comics>
        <isbn identifier="ISBN-13">978-1779515179</isbn>
        <name>The Sandman</name>
        <author ref="a3"/>
        <cover>Illustrated paperback</cover>
        <details>
            <genres> 
                <genre>Fantasy</genre>
                <genre>Fiction</genre>
            </genres>
            <pages>560</pages>
            <priceChange>20.99 15.99 17.99</priceChange>
            <currency type="Euros"/>
            <amount>7</amount>
            <publicationdate>2022-04-12</publicationdate>
            <readingAge limit="Mature">16</readingAge>
        </details>
    </comics>
 </books>
</Bookstore>
